language: ruby
cache: bundler
rvm:
  - 2.1.2
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree

env:
  - DB=sqlite
  - DB=postgresql

services:
  - redis-server

before_install:
  - gem update --system
  - gem --version

before_script:
  # - bundle exec rake db:setup

script:
  - bundle exec rake
  - bundle exec rspec

after_script:
  # - bundle exec rake db:setup

#branches: #BE CAREFUL
#  only:
#    - master
#    - sprint
